build:
    image: default-bionic
    environment:
        php: 8.1.2
    tests:
        override:
            - php-scrutinizer-run

tools:
    external_code_coverage: true

filter:
    excluded_paths:
        - 'tests/'
    dependency_paths:
        - 'vendor/'
